database:
  host: 0.0.0.0
  port: 3306
  databaseName: 'database'
  username: 'user'
  password: 'password'
gui:
  title: ''
  SwiftBlade:
    image: B
    head: "e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTNlZTJhYjI1YTE2ZGFjYjY5MzEwZDNmNDQ3NjE4NmE2YzJmNjc3MWQxOWM4ZDcwMWUwYTJkY2MxNzkxMzQ2ZiJ9fX0="