name: GardensRPG
version: 1.0.0
author: Bright_Steel
main: com.gardensmc.gardensrpg.GardensRPG
api-version: 1.19
softdepend:
  - PlaceholderAPI
depend:
  - NBTAPI
  - GardensFurniture
commands:
  bladebringer:
    description: Open bladebringers selection menu
    aliases:
      - bladebringers
      - bb
  playerprofile:
    description: Open playerprofile menu
    aliases: [profile]
